### ISSUE TITLE
DB schema: lacking people information

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#1]
Hi N.Game,
I'm Long from Nimble 👋 I have some comments regarding the design of the DB:

In the requirements, there is a sentence that says:
> For instructors, they have to specify **the instructor ID** and the **department name**. For students, they have to specify their **student ID**

I imported the [DB schema](https://github.com/mcneto/onlinecourse_project/blob/63b07d256b924bcfc3ed6e84c4f135629124aee1/db/schema.rb) in this project to dbdiagram.io: https://dbdiagram.io/d/5fe561599a6c525a03bc41ad

<img width="1097" alt="Screen Shot 2021-04-05 at 12 31 29" src="https://user-images.githubusercontent.com/1896814/113540686-dc03ad80-960a-11eb-84ce-6aa06b7a73b2.png">

but it looks like the above requirement wasn't handled by the current schema.

**Comment by mcneto** [comment]
At first I couldn’t figure out how to integrate roles into the project yet so I simply designed database to support only basic required information that all the roles need to fill. 

Because I didn’t want the database to be too complicated and after the role part was applied into the project later I didn’t update it which it’s my own oversight and there’re also some following complex issues which I wasn't sure how to handle it.

**Comment by longnd** [comment]
I'm curious that if you continue to work on this, how do you plan to store that information?
> For instructors, they have to specify the instructor ID and the department name. For students, they have to specify their student ID

**Comment by mcneto** [comment]
I didn’t have much experiences with database but for myself I might use json field in database to store profile information which include all the data if it can be use perfectly fine in rails project.

Example of Json data to store in database: 
{	
	first_name: 
	last_name:
	citizen_id:
	info: { instructor_id, department_name } // { student_id }
}

My new plan for database design: https://dbdiagram.io/d/606f38adecb54e10c33f602c
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/70894675/114068609-4e54e600-98c8-11eb-9f0f-7418abc31c2e.png">
