### ISSUE TITLE
Coding style: inconsistent format

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#5]
While it isn't required to follow a specific coding convention, but at least the code format should be consistent right?
This class is mixed of 4 spaces index (for the methods) and 2 spaces index (within each method)
https://github.com/mcneto/onlinecourse_project/blob/63b07d256b924bcfc3ed6e84c4f135629124aee1/app/controllers/users_controller.rb#L1-L19

same for this class that is a mix of 4 spaces & 2 spaces indents
https://github.com/mcneto/onlinecourse_project/blob/63b07d256b924bcfc3ed6e84c4f135629124aee1/app/controllers/application_controller.rb#L1-L12

**Comment by mcneto** [comment]
It was my flaw in this part as the beginning I have used a formatter extension in vs code to took care of this part but I had a problem as it stopped functioning in later and I also didn’t come back to inspect this after that. I will pay more attention to the consistency of the code format next time.
