### ISSUE TITLE
What is the purpose of "Toggle instructor rights" button?

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#7]
In the profile edit screen of an instructor, there is a button to "toggle the instructor right". Why do we need it?
<img width="375" alt="Screen Shot 2021-04-05 at 16 29 32" src="https://user-images.githubusercontent.com/1896814/113559739-1c275800-962c-11eb-8dac-b6184c691155.png">

**Comment by mcneto** [comment]
The Instructor can’t perform any action they have right to do until they toggle this button so the instructor_rights set to be true, it is false by default. This complexity is due to the redundant problems in the #2 issue as there’re 2 variables manage the role function.

**Comment by longnd** [comment]
This implementation is quite weird since an instructor can google his own role 😅
I have a comment https://github.com/mcneto/onlinecourse_project/issues/2#issuecomment-815513674. Please have a look.
