### ISSUE TITLE
Authorization on the views

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#8]
Since we're using Pundit for authorization, it should be applied to the views so the control elements (buttons) that are not suitable for the current users shouldn't be rendered. In this screenshot, a logged-in student can't Create/Edit/Delete a course so we shouldn't render those buttons
<img width="460" alt="Screen Shot 2021-04-05 at 16 34 12" src="https://user-images.githubusercontent.com/1896814/113560202-cef7b600-962c-11eb-9300-cc6bc959a1a9.png">

Refer to Pundit documentation on how to do that: https://github.com/varvet/pundit#policies with example:
```ruby
<% if policy(@post).update? %>
  <%= link_to "Edit post", edit_post_path(@post) %>
<% end %>
```

**Comment by mcneto** [comment]
I have already applied this into the course page, only the instructor who created a course will see and can perform the functions. 

Student and Instructor who doesn't has a right will see only show option:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/70894675/113693815-354a0a80-96f9-11eb-8246-e7d1c30c83b9.png">


Instructor who has a right will see all the options available:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/70894675/113693729-1f3c4a00-96f9-11eb-923d-6cc07a6174a7.png">


But as the group page was created last. It was my failure to check and cover it when I did an UI testing.

**Comment by longnd** [comment]
> I have already applied this into the course page

I saw that. But on the page to view a specific course, there is still a button to edit the course regardless of the role of the current user. I think you aware of that but didn't have enough time to implement it?

I have the same assumption for the other parts of the page, e.g. when viewing the list course, any instructors can see all courses & all students.

**Comment by mcneto** [comment]
I meant for everyone to see all the course so they can subscribe or view information about other courses as well but who can edit should be the owner only. (I'll fixed the edit button showing when viewing a specific coursed regardless of the role and ownership of the current user.)

But for the student list and group page, they weren't linked to the coursed page yet and can only be performed some basic functions right now so there's not much authorization were implemented to these pages.
