### ISSUE TITLE
Redundant "User ID" field in the Course creation form

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#9]
<img width="760" alt="Screen Shot 2021-04-05 at 16 49 30" src="https://user-images.githubusercontent.com/1896814/113561508-e8016680-962e-11eb-92b6-9a4dfea4f495.png">
Since we'll always set the user (who created the course) as the current user (line 27), the above field in the form is redundant and has no effect

https://github.com/mcneto/onlinecourse_project/blob/63b07d256b924bcfc3ed6e84c4f135629124aee1/app/controllers/courses_controller.rb#L25-L28

**Comment by mcneto** [comment]
The user_id field was automatic built when created the table. And I first wanted to adapt this part into an informative view but it was fall out from the planning when I wrapped up this page.
